# Project on Pneuma Club

In [3]:
pip install pandas

Requirement already satisfied: pandas in d:\pneuma\pneuma_travel_rewards_analytics_dataset\.venv\lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in d:\pneuma\pneuma_travel_rewards_analytics_dataset\.venv\lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\pneuma\pneuma_travel_rewards_analytics_dataset\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\pneuma\pneuma_travel_rewards_analytics_dataset\.venv\lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in d:\pneuma\pneuma_travel_rewards_analytics_dataset\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

In [5]:
users = pd.read_csv("users.csv")
points_accounts = pd.read_csv("points_accounts.csv")
searches = pd.read_csv("searches.csv")
award_results = pd.read_csv("award_results.csv")
clicks = pd.read_csv("clicks.csv")
booking_attempts = pd.read_csv("booking_attempts.csv")
bookings = pd.read_csv("bookings.csv")
subscriptions = pd.read_csv("subscriptions.csv")

In [10]:
users.head()

  user_id signup_date    city           user_type age_group
0   U0001  2026-05-17   Delhi   Frequent Traveler     35-44
1   U0002  2025-05-25  Jaipur     Casual Traveler     35-44
2   U0003  2025-07-20  Mumbai   Points Enthusiast     25-34
3   U0004  2026-04-06   Delhi   Frequent Traveler     18-24
4   U0005  2026-07-12    Pune  Premium Cardholder     18-24

In [6]:
users.shape

(500, 5)

# Dndersting the Data

In [7]:
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      500 non-null    str
 1   signup_date  500 non-null    str
 2   city         500 non-null    str
 3   user_type    500 non-null    str
 4   age_group    500 non-null    str
dtypes: str(5)
memory usage: 19.7 KB

In [8]:
users.describe()

       user_id signup_date  city           user_type age_group
count      500         500   500                 500       500
unique     500         333     8                   4         4
top      U0001  2025-03-19  Pune  Premium Cardholder     25-34
freq         1           5    73                 179       221

In [9]:
users.isnull().sum()

user_id        0
signup_date    0
city           0
user_type      0
age_group      0
dtype: int64

In [10]:
users["user_id"].duplicated().sum()         # check duplicate users

np.int64(0)

In [11]:
users.duplicated().sum()

np.int64(0)

# Categorical Data Analysis

In [12]:
users["city"].value_counts()            #City-wise users

city
Pune         73
Mumbai       69
Bengaluru    69
Delhi        68
Chennai      60
Kolkata      56
Jaipur       54
Hyderabad    51
Name: count, dtype: int64

In [13]:
users["user_type"].value_counts()                   # User type-wise users

user_type
Premium Cardholder    179
Frequent Traveler     114
Casual Traveler       106
Points Enthusiast     101
Name: count, dtype: int64

In [14]:
users["age_group"].value_counts()       #Age group-wise users

age_group
25-34    221
35-44    145
18-24     85
45+       49
Name: count, dtype: int64

# Insights from the Data

In [15]:
users["city"].value_counts(normalize=True) * 100            # % according to cities

city
Pune         14.6
Mumbai       13.8
Bengaluru    13.8
Delhi        13.6
Chennai      12.0
Kolkata      11.2
Jaipur       10.8
Hyderabad    10.2
Name: proportion, dtype: float64

In [16]:
users["user_type"].value_counts(normalize=True) * 100     # % according to Users type

user_type
Premium Cardholder    35.8
Frequent Traveler     22.8
Casual Traveler       21.2
Points Enthusiast     20.2
Name: proportion, dtype: float64

In [17]:
users["age_group"].value_counts(normalize=True) * 100           # % according to Age group

age_group
25-34    44.2
35-44    29.0
18-24    17.0
45+       9.8
Name: proportion, dtype: float64

# Moving to Search Data

In [18]:
searches.head(10)

,search_id,user_id,origin,destination,search_date,travel_date,cabin,device
0,S000001,U0320,Delhi,Dubai,2026-01-09,2026-03-08,Economy,Mobile
1,S000002,U0095,Delhi,New York,2026-01-08,2026-06-03,Business,Desktop
2,S000003,U0473,Mumbai,Dubai,2026-04-20,2026-05-15,Business,Desktop
3,S000004,U0361,Mumbai,Paris,2026-05-27,2026-08-16,Economy,Mobile
4,S000005,U0013,Delhi,Singapore,2026-02-20,2026-07-06,Business,Mobile
5,S000006,U0146,Hyderabad,Dubai,2026-07-19,2026-09-18,Economy,Desktop
6,S000007,U0405,Delhi,London,2026-08-14,2026-09-04,First,Mobile
7,S000008,U0368,Mumbai,Paris,2026-07-04,2026-10-18,First,Desktop
8,S000009,U0065,Bengaluru,London,2026-07-15,2026-09-28,First,Mobile
9,S000010,U0228,Delhi,Paris,2026-01-31,2026-06-29,Business,Desktop

In [19]:
searches.shape              # check rows and columns

(6000, 8)

In [20]:
searches.info()                 # Column information

<class 'pandas.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   search_id    6000 non-null   str
 1   user_id      6000 non-null   str
 2   origin       6000 non-null   str
 3   destination  6000 non-null   str
 4   search_date  6000 non-null   str
 5   travel_date  6000 non-null   str
 6   cabin        6000 non-null   str
 7   device       6000 non-null   str
dtypes: str(8)
memory usage: 375.1 KB

In [21]:
searches.isnull().sum()             # check missing values

search_id      0
user_id        0
origin         0
destination    0
search_date    0
travel_date    0
cabin          0
device         0
dtype: int64

In [22]:
searches["search_id"].duplicated().sum()            # check duplicate values

np.int64(0)

# Finding most popular Routes

In [23]:
searches.groupby(
    ["origin", "destination"]
).size().sort_values(ascending=False)

origin     destination
Delhi      Dubai          648
           London         614
Mumbai     Dubai          608
Delhi      Singapore      491
Mumbai     Singapore      447
           London         445
Bengaluru  London         379
Delhi      Paris          371
           New York       324
           Bangkok        322
Mumbai     Paris          307
           New York       306
Bengaluru  Dubai          281
Hyderabad  Dubai          234
Delhi      Tokyo          223
dtype: int64

In [24]:
# Analyze which airlines users encounter most frequently in the award results
award_results["airline"].value_counts()

airline
Air Canada            886
Emirates              877
Lufthansa             874
United Airlines       865
Etihad Airways        856
Air India             856
Singapore Airlines    852
Qatar Airways         844
Name: count, dtype: int64

In [25]:
# Analyze the demand for different cabin classes
searches["cabin"].value_counts()

cabin
Economy     3070
Business    2433
First        497
Name: count, dtype: int64

In [26]:
# Check the availability status of award results
award_results["availability"].value_counts()

availability
Available    6910
Name: count, dtype: int64

In [27]:
# Calculate the award availability rate
availability_rate = (
    award_results["availability"].value_counts(normalize=True) * 100                
)

availability_rate               

# To calculate award availability rate we use a formula
#  Total available award results ÷ Total award results × 100

availability
Available    100.0
Name: proportion, dtype: float64

In [28]:
# Analyze the most popular travel destinations
searches["destination"].value_counts()

destination
Dubai        1771
London       1438
Singapore     938
Paris         678
New York      630
Bangkok       322
Tokyo         223
Name: count, dtype: int64

# Monthly Search Trend 📈

In [29]:
# Convert search_date to datetime format
searches["search_date"] = pd.to_datetime(searches["search_date"])

In [30]:
# Analyze the number of searches by month
searches["search_date"].dt.to_period("M").value_counts().sort_index()

search_date
2026-01    744
2026-02    707
2026-03    794
2026-04    742
2026-05    766
2026-06    735
2026-07    794
2026-08    718
Freq: M, Name: count, dtype: int64

# Booking Conversion Rate

In [31]:
# Calculate the search-to-booking conversion rate
conversion_rate = (bookings["search_id"].nunique() / searches["search_id"].nunique()) * 100

conversion_rate

# Conversion Rate = Unique searches that resulted in a booking ÷ Total unique searches × 100

9.333333333333334

# Subscription Analysis 💰

In [32]:
# Analyze the distribution of subscription plans
subscriptions["plan"].value_counts()

plan
Monthly    101
Annual      50
Name: count, dtype: int64

In [33]:
# Analyze revenue generated by each subscription plan
subscriptions.groupby("plan")["revenue_inr"].sum().sort_values(ascending=False)

plan
Annual     249950
Monthly     50399
Name: revenue_inr, dtype: int64

In [34]:
# Merge subscription data with user information
user_subscription = subscriptions.merge(
    users[["user_id", "user_type"]],
    on="user_id",
    how="left"
)

In [35]:
# Analyze subscriptions by user type
user_subscription["user_type"].value_counts()

user_type
Premium Cardholder    56
Frequent Traveler     34
Casual Traveler       31
Points Enthusiast     30
Name: count, dtype: int64

In [36]:
# Calculate the subscription rate for each user type
subscription_rate = (
    user_subscription.groupby("user_type")["user_id"]
    .nunique()
    .div(users.groupby("user_type")["user_id"].nunique())
    * 100
)

subscription_rate.sort_values(ascending=False)

user_type
Premium Cardholder    31.284916
Frequent Traveler     29.824561
Points Enthusiast     29.702970
Casual Traveler       29.245283
Name: user_id, dtype: float64

In [37]:
# Analyze total miles redeemed by each airline
bookings.merge(
    award_results[["result_id", "airline"]],
    on="result_id",
    how="left"
).groupby("airline")["miles_used"].sum().sort_values(ascending=False)

airline
Singapore Airlines    6340811
Lufthansa             6297158
Qatar Airways         6035707
Emirates              5902848
Air Canada            5738789
Air India             5681965
United Airlines       5487109
Etihad Airways        4741459
Name: miles_used, dtype: int64

In [38]:
# Calculate the total miles redeemed
bookings["miles_used"].sum()

np.int64(46225846)

In [39]:
# Calculate the total taxes paid for bookings
bookings["taxes_paid_inr"].sum()

np.int64(6364781)

In [40]:
# Calculate the average miles redeemed per booking
bookings["miles_used"].mean()

np.float64(79975.51211072665)

In [41]:
# Calculate the average taxes paid per booking
bookings["taxes_paid_inr"].mean()

np.float64(11011.731833910035)

In [42]:
# Identify users who performed more than one search
searches_per_user = searches.groupby("user_id")["search_id"].count()

repeat_users = (searches_per_user > 1).sum()

repeat_users

np.int64(500)

In [43]:
# Identify the most active users based on search activity
searches_per_user.sort_values(ascending=False).head(10)

user_id
U0246    23
U0399    22
U0428    21
U0244    21
U0271    21
U0220    21
U0405    21
U0015    20
U0189    20
U0308    20
Name: search_id, dtype: int64

In [44]:
# Analyze the routes with the highest number of bookings
bookings.merge(
    searches[["search_id", "origin", "destination"]],
    on="search_id",
    how="left"
).groupby(
    ["origin", "destination"]
).size().sort_values(ascending=False).head(10)

origin     destination
Delhi      London         67
           Singapore      59
           Dubai          56
Mumbai     London         51
           Dubai          50
           Singapore      47
Bengaluru  London         40
Delhi      Paris          35
Mumbai     New York       31
Delhi      New York       30
dtype: int64